FROM python:3.13
WORKDIR /usr/local/app

# Install the application dependencies
COPY requirements.txt ./
COPY gunicorn.conf.ini ./
RUN pip3 install --no-cache-dir -r requirements.txt


# Copy in the source code
COPY src ./src
EXPOSE 1500

# Setup an app user so the container doesn't run as the root user
RUN useradd app
USER app

# gunicorn -w 4 -b :1500 'app:create_app()' -c gunicorn.conf.ini   
CMD ["gunicorn", "-w", "4", "-b", ":1500",  "app:create_app()", "-c", "gunicorn.conf.ini"]