FROM python:3.11
WORKDIR /usr/local/app



# Install the application dependencies
COPY requirements.txt ./
COPY gunicorn.conf.py ./
RUN sudo apt update && sudo apt install supervisor
RUN pip3 install --no-cache-dir -r requirements.txt

# start supervisor



# Copy in the source code
COPY src ./src
COPY app.py app.py
COPY routes.py routes.py
COPY run_pipeline.py run_pipeline.py
COPY eduthemes-gunicorn.conf /etc/supervisor/conf.d/eduthemes-gunicorn.conf
EXPOSE 1500

# Setup an app user so the container doesn't run as the root user
RUN useradd app
RUN chown -R app:app /usr/local/app
USER app

RUN sudo service supervisor start

# gunicorn -w 4 -b :1500 'app:create_app()' -c gunicorn.conf.ini   

CMD ["gunicorn", "-w", "4", "-b", ":1500",  "app:create_app()", "-c", "gunicorn.conf.py"]